# Конфигурация TLS (сертификаты)
# Этот файл говорит Traefik, где лежат файлы сертификата и ключа.
# Пути указаны ВНУТРИ контейнера (см. volumes в docker-compose.yml)

tls:
  certificates:
    - # Путь к файлу сертификата внутри контейнера
      certFile: "/etc/certs/cert.crt"
      # Путь к файлу приватного ключа внутри контейнера
      keyFile: "/etc/certs/cert.key"